spring:
  application:
    name: chat-service2
  data:
    mongodb:
      host: localhost
      port: 27017
      database: authenticationDb
      username: abdelrahman
      password: abdelrahman
      authentication-database: admin


server:
  port: 9070


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka