spring:
  application:
    name: chat-service
    instance:
      id: instance-two   # each new instance should have a unique id because it's related to specific kafka topic partition
  data:
    mongodb:
      host: localhost
      port: 27017
      database: authenticationDb
      username: abdelrahman
      password: abdelrahman
      authentication-database: admin

server:
  port: 9098

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

getway:
  url: http://localhost:8222
